//Update here
service: microservice-openweather-nodejs-jest-aws

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(./serverless-ssm.yml)}

plugins:
  - serverless-offline-ssm
  - serverless-offline

functions:
  getWeatherCondition:
    handler: src/controllers/weather-condition/get.handler
    events:
      - http:
          path: /v1/weather-condition/country/{country}
          method: get
          private: false
          
custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
  serverless-offline-ssm:
    stages:
      - dev
    ssm: ${file(./serverless-ssm.yml)}
