
service: microservice-openweather-nodejs-jest-aws

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 30
  environment: ${file(./serverless-ssm.yml)}

plugins:
  - serverless-offline-ssm
  - serverless-offline

functions:
  getWeather:
    handler: src/controllers/weather/get.handler
    events:
      - http:
          path: /v1/weather/location/{location}
          method: get
          private: false
          
  getEnhancedWeather:
    handler: src/controllers/weather/enhanced.handler
    events:
      - http:
          path: /v1/weather-enhanced/location/{location}
          method: get
          private: false
          
  getForecast:
    handler: src/controllers/forecast/get.handler
    events:
      - http:
          path: /v1/forecast/location/{location}
          method: get
          private: false
          
  getEnhancedForecast:
    handler: src/controllers/forecast/enhanced.handler
    events:
      - http:
          path: /v1/forecast-enhanced/location/{location}
          method: get
          private: false
          
  getAirPollution:
    handler: src/controllers/air-pollution/get.handler
    events:
      - http:
          path: /v1/air-pollution/location/{location}
          method: get
          private: false
          
  getEnhancedAirPollution:
    handler: src/controllers/air-pollution/enhanced.handler
    events:
      - http:
          path: /v1/air-pollution-enhanced/location/{location}
          method: get
          private: false
          
  healthCheck:
    handler: src/controllers/health/check.handler
    events:
      - http:
          path: /health
          method: get
          private: false
          
custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
  serverless-offline-ssm:
    stages:
      - dev
    ssm: ${file(./serverless-ssm.yml)}
